version: '2'

networks:
  appnet:
    external:
      name: etcds

services:
#  micro:
#    command: micro server & && micro --registry=etcd --registry_address=etcd1:2379 api --handler=rpc
#    image: micro/micro:latest
#    ports:
#      - "8080:8080"
#    networks:
#      - appnet

  api:
    build: ./api/hotel
    command:  --registry=etcd --registry_address=etcd1:2379
    networks:
      - appnet

  auth:
    build: services/auth
    command:  --registry=etcd --registry_address=etcd1:2379
    networks:
      - appnet

  geo:
    build: services/geo
    command:  --registry=etcd --registry_address=etcd1:2379
    networks:
      - appnet

  profile:
    build: services/profile
    command:  --registry=etcd --registry_address=etcd1:2379
    networks:
      - appnet

  rate:
    build: services/rate
    command:  --registry=etcd --registry_address=etcd1:2379
    networks:
      - appnet

